worker_processes auto;
error_log /var/log/nginx/error.log;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1920;
        chunk_size 4096;

        application live {
            live on;
            record all;
            record_path /tmp/recordings;
            record_unique on;

            on_publish http://host.docker.internal:3086/api/streaming/publish;
            on_publish_done http://host.docker.internal:3086/api/streaming/publish_done;
            on_play http://host.docker.internal:3086/api/streaming/play;
            on_play_done http://host.docker.internal:3086/api/streaming/play_done;
        }
    }
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
